### ISSUE TITLE
Table re-rending

### ISSUE THREAD

**Issue by ghwoo93** [joadan/TabBlazor#12]
Hi

I tried to render different number of columns in one component. However, because the number of columns in the component is not re-rendered, an outOfRange Error occurs. So I tried calling HasStateChanged() but it didn't work. Is there any way to re-render the table component?

**Comment by joadan** [comment]
Hi,

There is an _Update_ method on the table, check if that helps.

**Comment by ghwoo93** [comment]
Hi,
Thanks for your solution.

In the work I'm currently working on, there is a problem that the columns included in the table are not redrawn. The way to express the floating column now is to set the maximum number of columns on the system and initially allocate it with a size of 100px. Then, allocate the pixel of the column required for the data set and 0px for the column that is not needed.
This process is repeated in the process of inquiring the data set. For example, the maximum number of columns supported by the system is set to 12. In this case, it is not a problem to look up a dataset of 6 and then a dataset of 12. However, when searching for a 6-piece data set and then searching for a 12-piece dataset, the column is not drawn even if the pixel of 0px column is allocated again and updated.
My guess is that if you set it to 0px, the problem is that the column itself disappears from rendering. Is this correct?

**Comment by joadan** [comment]
Hi,

Not sure I follow, but no column should be removed if the width is 0px. 
Could you share a sample that reproduce the issue?

**Comment by joadan** [comment]
clean up
