### ISSUE TITLE
When scrolled to the top of a page and opening a modal the page content shifts down about 10px

### ISSUE THREAD

**Issue by jacobpihl** [joadan/TabBlazor#15]
To reproduce:
Go to documentation: [Modals Docs](https://tabblazor.com/docs/modals)
Make sure you are scrolled all the way up and press the button to open a modal.
All the content except the navbar will shift downwards.

**Comment by joadan** [comment]
Fixed in v0.4.4-alpha

**Comment by jacobpihl** [comment]
Confirmed works.
