### ISSUE TITLE
Browser console error

### ISSUE THREAD

**Issue by marcelokrol** [joadan/TabBlazor#21]
Hello
I'm getting the below error in the browser console when adding the DropDown component or a Select.
I copied the example just like the DOCs project, but I think it must be missing some reference, but I'm not able to find the fault.

`blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'tabBlazor.clickOutsideHandler.addEvent' ('tabBlazor' was undefined).
      Error: Could not find 'tabBlazor.clickOutsideHandler.addEvent' ('tabBlazor' was undefined).
          at https://localhost:44315/_framework/blazor.webassembly.js:1:1287
          at Array.forEach (<anonymous>)
          at e.findFunction (https://localhost:44315/_framework/blazor.webassembly.js:1:1247)
          at b (https://localhost:44315/_framework/blazor.webassembly.js:1:2989)
          at https://localhost:44315/_framework/blazor.webassembly.js:1:3935
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:44315/_framework/blazor.webassembly.js:1:3908)
          at Object.w [as invokeJSFromDotNet] (https://localhost:44315/_framework/blazor.webassembly.js:1:64232)
          at _mono_wasm_invoke_js_blazor (https://localhost:44315/_framework/dotnet.5.0.12.js:1:190800)
          at do_icall (wasm://wasm/00aba242:wasm-function[10596]:0x194e4e)
Microsoft.JSInterop.JSException: Could not find 'tabBlazor.clickOutsideHandler.addEvent' ('tabBlazor' was undefined).
Error: Could not find 'tabBlazor.clickOutsideHandler.addEvent' ('tabBlazor' was undefined).
    at https://localhost:44315/_framework/blazor.webassembly.js:1:1287
    at Array.forEach (<anonymous>)
    at e.findFunction (https://localhost:44315/_framework/blazor.webassembly.js:1:1247)
    at b (https://localhost:44315/_framework/blazor.webassembly.js:1:2989)
    at https://localhost:44315/_framework/blazor.webassembly.js:1:3935
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:44315/_framework/blazor.webassembly.js:1:3908)
    at Object.w [as invokeJSFromDotNet] (https://localhost:44315/_framework/blazor.webassembly.js:1:64232)
    at _mono_wasm_invoke_js_blazor (https://localhost:44315/_framework/dotnet.5.0.12.js:1:190800)
    at do_icall (wasm://wasm/00aba242:wasm-function[10596]:0x194e4e)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15'1[[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at TabBlazor.ClickOutside.OnAfterRenderAsync(Boolean firstRender) in D:\dev\TabBlazor\src\TabBlazor\Components\Utilities\ClickOutside.razor:line 22
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)`

**Comment by joadan** [comment]
Hi,

Looks like you are missing to add the TabBlazor javascript, something like this 

<script src="_content/TabBlazor/js/tabblazor.js"></script>

**Comment by marcelokrol** [comment]
Hello Joadan
I think I did something wrong. I looked in the sources like you do to refer to 'tabblazor.js' and I didn't find it. So I copied the file to the Client project's wwwroot\js folder, but it still didn't solve the problem.
Would it be possible to provide an example, preferably using the dll installed by the nuget package?

**Comment by joadan** [comment]
Hello,

I'm sorry I realized my answer was not clear. I will try to update the documentation to show a step to step guide to get started. 
Until that is done I think the easiest way is to look in this repo in the docs projects https://github.com/joadan/TabBlazor/tree/master/docs

**Comment by eksotama** [comment]
> Hello I'm getting the below error in the browser console when adding the DropDown component or a Select. I copied the example just like the DOCs project, but I think it must be missing some reference, but I'm not able to find the fault.
> 
> `blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100] Unhandled exception rendering component: Could not find 'tabBlazor.clickOutsideHandler.addEvent' ('tabBlazor' was undefined). Error: Could not find 'tabBlazor.clickOutsideHandler.addEvent' ('tabBlazor' was undefined). at https://localhost:44315/_framework/blazor.webassembly.js:1:1287 at Array.forEach (<anonymous>) at e.findFunction (https://localhost:44315/_framework/blazor.webassembly.js:1:1247) at b (https://localhost:44315/_framework/blazor.webassembly.js:1:2989) at https://localhost:44315/_framework/blazor.webassembly.js:1:3935 at new Promise (<anonymous>) at Object.beginInvokeJSFromDotNet (https://localhost:44315/_framework/blazor.webassembly.js:1:3908) at Object.w [as invokeJSFromDotNet] (https://localhost:44315/_framework/blazor.webassembly.js:1:64232) at _mono_wasm_invoke_js_blazor (https://localhost:44315/_framework/dotnet.5.0.12.js:1:190800) at do_icall (wasm://wasm/00aba242:wasm-function[10596]:0x194e4e) Microsoft.JSInterop.JSException: Could not find 'tabBlazor.clickOutsideHandler.addEvent' ('tabBlazor' was undefined). Error: Could not find 'tabBlazor.clickOutsideHandler.addEvent' ('tabBlazor' was undefined). at https://localhost:44315/_framework/blazor.webassembly.js:1:1287 at Array.forEach (<anonymous>) at e.findFunction (https://localhost:44315/_framework/blazor.webassembly.js:1:1247) at b (https://localhost:44315/_framework/blazor.webassembly.js:1:2989) at https://localhost:44315/_framework/blazor.webassembly.js:1:3935 at new Promise (<anonymous>) at Object.beginInvokeJSFromDotNet (https://localhost:44315/_framework/blazor.webassembly.js:1:3908) at Object.w [as invokeJSFromDotNet] (https://localhost:44315/_framework/blazor.webassembly.js:1:64232) at _mono_wasm_invoke_js_blazor (https://localhost:44315/_framework/dotnet.5.0.12.js:1:190800) at do_icall (wasm://wasm/00aba242:wasm-function[10596]:0x194e4e) at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15'1[[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args) at TabBlazor.ClickOutside.OnAfterRenderAsync(Boolean firstRender) in D:\dev\TabBlazor\src\TabBlazor\Components\Utilities\ClickOutside.razor:line 22 at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)`

Please run console from publish folder. It's solved for me

**Comment by joadan** [comment]
Hi, 

I have now creates a TabBlazor Templates repository, please have a look at https://github.com/joadan/TabBlazor.Templates 
Here its possible to get a Wasm or Server Template to get started.

**Comment by marcelokrol** [comment]
Hello. I was very happy with your contribution and readiness to make the examples available. The only detail is that you created them in NET 6, and we don't have the necessary structure to migrate from 5 to 6 at the moment. I'm resuming the project today, and I'll try to make the necessary adaptation for 5, so that I can run the examples on my machine. But once again thank you very much!!!

**Comment by joadan** [comment]
Clean up
