### ISSUE TITLE
Can't find code at Tabler.Docs.Server\Tabler.Docs\Components\_NameOfComponent_

### ISSUE THREAD

**Issue by eksotama** [joadan/TabBlazor#32]
How to fixed error :
Unable to find code at D:\TabBlazor-master\TabBlazor-master\docs\Tabler.Docs.Server\Tabler.Docs\Components\.....

**Comment by joadan** [comment]
Hi, 

Are you getting this error when you try to run it locally?

**Comment by eksotama** [comment]
Yes, it's
Please info to solve this..

**Comment by joadan** [comment]
Hi 

Not really sure but if you compare the path in the message with the actual path to the source code on your disk it would easier to understand what the problem is.

Do you get source code if you run the Tabler.Docs.Wasm project? 
The wasm project is using github as a source for the source code.

**Comment by joadan** [comment]
clean up
