### ISSUE TITLE
<FooterTemplate> in ItemSelect demo is disconnected from dropdown

### ISSUE THREAD

**Issue by jacobpihl** [joadan/TabBlazor#34]
![image](https://user-images.githubusercontent.com/6748229/152646616-085ba7d3-95c6-4dae-bb70-61228affab02.png)

See image.
This is in the "Templates" Demo for Item Select: https://tabblazor.com/docs/forms/item-selects

Problem is not present in my own code when using `<FooterTemplate>`.

**Comment by joadan** [comment]
Only in Firefox

**Comment by jacobpihl** [comment]
I'm happy with the solution. Closing this issue.
