### ISSUE TITLE
how to use different icon providers with NavbarMenuItem 

### ISSUE THREAD

**Issue by developer9969** [joadan/TabBlazor#35]
Hi I am new to blazor and  I came across TabBlazor , I really like it, but struggling with few things.

Lets suppose I wanted to use a different icon provider I.E google materials etc.. 
Once I have imported all the files in the css folder , how can the  NavbarMenuItem be changed to use a different icon provider?

How can I generate the path etc.. from google material icons  to add to the icons class?

Any suggestions?
Many thanks

**Comment by developer9969** [comment]
Hi thanks for replying  that would be great and even more Interested on how u generate them.

I am trying to build an admin site and yours drew my attention because there was little or no js.

I am not a we b developer so harder for me , one  thing that I noticed is that you don't have a burger menu that collapse..
Also the reason I would like to use yours is that I suppose I could use straight bootstrap and learn a bit  that is why I don't want to use mudblazor.

Anyway if you could provide the paths that would be great and next I need to figure out how to add the burger menu that collapses.. unles u did already.

**Comment by joadan** [comment]
Hello,

I have now done some work on Icons.
If you check the https://tabblazor.com/docs/icons - Icon List, you will now see Tabler and Material Design Icons. 

The project for generating the icons are here, https://github.com/joadan/TabBlazor/tree/master/Icons/IconGenerator
This is not released I'm still have some more things to work out.

**Comment by developer9969** [comment]
Hi
that is good stuff !!!  
the main thing in your framework that is missing  is the burger menu.

**Comment by joadan** [comment]
clean up
