### ISSUE TITLE
Table data formats

### ISSUE THREAD

**Issue by KhurshidRustamov** [joadan/TabBlazor#39]
Hi

I can't find way for format decimal, please help

**Comment by joadan** [comment]
Hello,

There is a <Template> template that you can use in a column to specify how to format the cell content.

Something like this:
`
<Column Item="Order" Property="e=>e.NetValue" Title="Value" Sortable Searchable>
<Template>
       $@context.NetValue.ToString("N0")
 </Template>
</Column>
`

**Comment by KhurshidRustamov** [comment]
works fine, thnks
