### ISSUE TITLE
Ability to cycle sorting mode to 'off' on table column

### ISSUE THREAD

**Issue by Inoii** [joadan/TabBlazor#51]
Currently once you click a table column the sorting is always 'on' with no way of turning it off.

Proposed solution:
Cycle though ascending, descending and then "off"
![TBIssue](https://user-images.githubusercontent.com/54079606/171167318-9fbd1635-5c9d-47f7-a283-05da858f3fd2.PNG)

**Comment by jacobpihl** [comment]
Issue resolved in release v0.6.1-alpha
