### ISSUE TITLE
Offline use

### ISSUE THREAD

**Issue by Nachtwind85** [joadan/TabBlazor#55]
Hi, 

currently TabBlazor uses 
`<link rel="stylesheet" href="https://unpkg.com/@tabler/core@1.0.0-beta2/dist/css/tabler.min.css">`
in the HEAD area... which is unfortunate since we want to use this template for a intranet application that has no internet connection whatsoever.

Therefore in pure intranet environments the Template is broken and wont work.

Is it possible to add, rather soonish, a switch to disable this link and provide the CSS offline by hand?

**Comment by joadan** [comment]
Hello,

You can just copy the content of the css and place it in a local file and reference that instead.

**Comment by Nachtwind85** [comment]
This is, basically, what i do right now. Unfortunately resolves the issue
only hald-heartedly because the first access to the page has a terrible
loading time as the connection times out.

Thanks

Am Di., 14. Juni 2022 um 07:47 Uhr schrieb Joakim Dangården <
***@***.***>:

**Comment by Nachtwind85** [comment]
Hi, Sorry that it took me a while to respond. 

In deed there was some black magic here.. our firewall/caching etc played tricks with me so despite "offlining" the css file it was still tried to get it from the online source. No idea how, no idea why but in the end it works now - as expected.
Thanks :)
