### ISSUE TITLE
Blurred background when Modal is opened shifts down 

### ISSUE THREAD

**Issue by PerryCodes** [joadan/TabBlazor#9]
Whenever I open a modal, the blurred background appears to move down about 10 or 15 px.  Can that be adjusted?

**Comment by joadan** [comment]
Hi,

Sorry but I'm not able to reproduce this.
Do you see this in the demo page [Model Demo](https://tabblazor.com/docs/modals)?

**Comment by joadan** [comment]
Fixed in v0.4.4-alpha
